version: '2'

volumes:
  spotifycache:
  thelounge:
  pihole_config:
  dnsmasq_config:

services:

  ### Balena Sound ###
  # Core services
  audio:
    build: ./modules/balena-sound/core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317

  sound-supervisor:
    build: ./modules/balena-sound/core/sound-supervisor
    network_mode: host
    ports:
      - 3000:3000
    labels:
      io.balena.features.supervisor-api: 1

  multiroom-server:
    build: ./modules/balena-sound/core/multiroom/server
    restart: on-failure
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780

  multiroom-client:
    build: ./modules/balena-sound/core/multiroom/client
    restart: on-failure

  # Plugins
  bluetooth:
    build: ./modules/balena-sound/plugins/bluetooth
    restart: on-failure
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1

  airplay:
    build: ./modules/balena-sound/plugins/airplay
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1

  spotify:
    build: ./modules/balena-sound/plugins/spotify
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - spotifycache:/var/cache/raspotify

  upnp:
    build: ./modules/balena-sound/plugins/upnp
    restart: on-failure
    network_mode: host
    ports:
      - 49494:49494

  ### The Lounge IRC ###
  lounge:
    build: ./modules/lounge
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - thelounge:/var/opt/thelounge

  ### Pi Hole ###
  # https://hub.docker.com/r/pihole/pihole
  pihole:
    build: ./modules/balena-pihole/pihole
    privileged: true
    volumes:
      - pihole_config:/etc/pihole
      - dnsmasq_config:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      - DNSMASQ_LISTENING=eth0
      - INTERFACE=eth0
      - DNS1=127.0.0.1#5053
      - DNS2=127.0.0.1#5053
      - ServerIP
    network_mode: host
    labels:
      io.balena.features.dbus: "1"

  # https://hub.docker.com/r/klutchell/unbound-dnscrypt
  unbound:
    build: ./modules/balena-pihole/unbound
    ports:
      - "5053:5053/udp"
